Messages about db packing' success/fail added

diff --git a/addcd b/addcd
--- a/addcd
+++ b/addcd
@@ -164,10 +164,13 @@ fi
 done # while true loop
 
 # copy database back and remove temp copy
+echo -n "Packing database... "
 bzip2 --stdout --best "$tmpdb" > "$db"
-if [ $? -eq 1 ]
+if [ $? -eq 0 ]
 then
-    echo "Database can't be packed!"
+    echo "done!"
+else
+    echo "failed!"
     exit 1
 fi
 rm "$tmpdb"
